version: '3.1'

services:
    dbPostgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: example
            POSTGRES_DB: mydb
        ports:
            - '5432:5432'
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
